#!/bin/sh
unset IFS
set -euf

SRC="${0%/*}"

# shellcheck source=/dev/null
. "${SRC}/manray-vars.sh"

usage() {
    echo "Usage: $0 <start|stop>"
    exit 1
}

if [ "$#" -ne 1 ]; then
    usage
fi

COMMAND="$1"

case "$COMMAND" in
start)
    if bootparams | grep '^smartos=true' >/dev/null; then
        for file in ${MANRAY_PERSISTENT_FILES}; do
            file_wallet="${MANRAY_WALLET}/$(basename "$file")"

            if [ ! -e "$file_wallet" ]; then
                cp "$file" "$file_wallet"
            fi

            cp "$file_wallet" "$file"
        done
    fi
    ;;
stop) ;;

*)
    usage
    ;;
esac
