#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

SRC="${0%/*}"
. "${SRC}/manray-vars.sh"

usage() {
    echo "Usage: $0 <start|stop>"
    exit 1
}

if [ "$#" -ne 1 ]; then
    usage
fi

COMMAND="$1"

case "$COMMAND" in
start)
    bootparams | grep '^smartos=true' >/dev/null
    if [ "$?" -eq 0 ]; then
        for file in ${MANRAY_PERSISTENT_FILES}; do
            file_wallet="${MANRAY_WALLET}/$(basename $file)"

            if [ ! -e "$file_wallet" ]; then
                cp "$file" "$file_wallet"
            fi

            cp "$file_wallet" "$file"
        done
    fi
    ;;
stop) ;;

*)
    usage
    ;;
esac
