#!/bin/sh
set -eu
IFS="$(printf '%b_' '\n\t ')"
IFS="${IFS%_}"

SRC="${0%/*}"
. "${SRC}/manray-vars.sh"

usage() {
    echo "Usage: $0 <start|stop>"
    exit 1
}

# Synchronize configuration files bidirectionally between a persisted manray wallet and read-only loopbacks.
#
# Usage: seal_wallet
seal_wallet() {
    bootparams | grep '^smartos=true' >/dev/null
    if [ "$?" -eq 0 ]; then
        for file in ${MANRAY_PERSISTENT_FILES}; do
            file_wallet="${MANRAY_WALLET}/$(basename $file)"

            mount -p | grep "$file" >/dev/null
            if [ "$?" -ne 0 ]; then
                cp "$file" "$file_wallet"
                mount -F lofs "$file_wallet" "$file"
            fi
        done
    fi
}

# Retract the persisted wallet for a transiently writeable edition of configuration files.
# Warning: Change will be lost a the next boot unless the wallet is explicitly sealed beforehand.
#
# Usage: unseal_wallet
unseal_wallet() {
    for file in ${MANRAY_PERSISTENT_FILES}; do
        file_wallet="${MANRAY_WALLET}/$(basename $file)"

        mount -p | grep "$file" >/dev/null
        if [ "$?" -eq 0 ]; then
            umount "$file"
            cp "$file_wallet" "$file"
        fi
    done
}

if [ "$#" -ne 1 ]; then
    usage
fi

COMMAND="$1"

case "$COMMAND" in
start)
    seal_wallet
    ;;
stop)
    unseal_wallet
    ;;
*)
    usage
    ;;
esac
