#!/bin/sh
unset IFS
set -euf

SRC="${0%/*}"

# shellcheck source=/dev/null
. "${SRC}/manray-vars.sh"

usage() {
    echo "Usage: $0 <start|stop>"
    exit 1
}

# Synchronize configuration files bidirectionally between a persisted manray wallet and read-only loopbacks.
#
# Usage: seal_wallet
seal_wallet() {
    if bootparams | grep '^smartos=true' >/dev/null; then
        for file in ${MANRAY_PERSISTENT_FILES}; do
            file_wallet="${MANRAY_WALLET}/$(basename "$file")"

            if mount -p | grep "$file" >/dev/null; then
                cp "$file" "$file_wallet"
                mount -F lofs "$file_wallet" "$file"
            fi
        done
    fi
}

# Retract the persisted wallet for a transiently writeable edition of configuration files.
# Warning: Change will be lost a the next boot unless the wallet is explicitly sealed beforehand.
#
# Usage: unseal_wallet
unseal_wallet() {
    for file in ${MANRAY_PERSISTENT_FILES}; do
        file_wallet="${MANRAY_WALLET}/$(basename "$file")"

        if mount -p | grep "$file" >/dev/null; then
            umount "$file"
            cp "$file_wallet" "$file"
        fi
    done
}

if [ "$#" -ne 1 ]; then
    usage
fi

COMMAND="$1"

case "$COMMAND" in
start)
    seal_wallet
    ;;
stop)
    unseal_wallet
    ;;
*)
    usage
    ;;
esac
